# Generated by Django 4.1 on 2022-10-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_remove_stock_itemcreation_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='stock_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroupcreation'),
        ),
    ]
