# Generated by Django 4.1 on 2022-10-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_stock_itemcreation_stock_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='stock_group',
        ),
        migrations.CreateModel(
            name='get_stock_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroupcreation')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_itemcreation')),
            ],
        ),
    ]
