# Generated by Django 4.1 on 2022-10-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_remove_stock_itemcreation_stock_group_get_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroupcreation'),
        ),
    ]
