# Generated by Django 4.1 on 2022-10-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_stock_itemcreation_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_item_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voucher_type', models.CharField(max_length=50)),
                ('Voucher_no', models.IntegerField()),
                ('inwards_qty', models.IntegerField()),
                ('inwards_val', models.IntegerField()),
                ('outwards_qty', models.IntegerField()),
                ('outwards_val', models.IntegerField()),
                ('closing_qty', models.IntegerField()),
                ('closing_val', models.IntegerField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroupcreation')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_itemcreation')),
            ],
        ),
        migrations.DeleteModel(
            name='get_stock_item',
        ),
    ]
