# Generated by Django 4.1 on 2022-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_stock_item_voucher_delete_get_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='Voucher_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='closing_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='closing_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='inwards_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='inwards_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='outwards_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='outwards_val',
            field=models.IntegerField(null=True),
        ),
    ]
