# Generated by Django 4.1 on 2022-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_stock_item_voucher_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='fmonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
            ],
        ),
    ]
