# Generated by Django 4.1 on 2022-11-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_fmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_voucher',
            name='month_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.fmonths'),
        ),
    ]
