# Generated by Django 4.1 on 2022-11-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_stock_item_voucher_month_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='closing_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='closing_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='inwards_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='inwards_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='month_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.fmonths'),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='outwards_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='outwards_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
