# Generated by Django 4.1 on 2022-11-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_alter_stock_item_voucher_closing_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_item_voucher',
            old_name='month_id',
            new_name='month',
        ),
    ]
