# Generated by Django 4.1 on 2022-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_rename_month_id_stock_item_voucher_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_voucher',
            name='Particulars',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
