# Generated by Django 4.1 on 2022-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_age_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age_analysis',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='age_analysis',
            name='negative_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
