# Generated by Django 4.1 on 2022-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_alter_age_analysis_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_analysis',
            name='total_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='age_analysis',
            name='total_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
