# Generated by Django 4.1 on 2022-12-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_age_analysis_total_qty_age_analysis_total_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_item_voucher',
            name='month',
        ),
        migrations.AddField(
            model_name='stock_item_voucher',
            name='month_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
