# Generated by Django 4.1 on 2022-12-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_remove_stock_item_voucher_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_item_voucher',
            name='month_name',
        ),
        migrations.AddField(
            model_name='stock_item_voucher',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.fmonths'),
        ),
    ]
