# Generated by Django 4.1 on 2022-12-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_remove_stock_item_voucher_month_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='group',
        ),
    ]
