# Generated by Django 4.1 on 2022-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_remove_stock_itemcreation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_voucher',
            name='per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock_item_voucher',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
