# Generated by Django 4.1 on 2022-12-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_remove_age_analysis_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age_analysis',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
