# Generated by Django 4.1 on 2022-12-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_alter_age_analysis_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='age_analysis',
        ),
    ]
