# Generated by Django 4.1 on 2022-12-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_delete_age_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_item_voucher',
        ),
    ]
