# Generated by Django 4.1 on 2022-12-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_stock_item_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.createstockgrp'),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='under',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.createstockgrp'),
        ),
        migrations.DeleteModel(
            name='stockgroupcreation',
        ),
    ]
