# Generated by Django 4.1 on 2022-12-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_alter_stock_itemcreation_under_stockgroupcreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='under',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.createstockgrp'),
        ),
    ]
